name: AppScan CodeSweep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CodeSweep:
    runs-on: ubuntu-latest
    name: Run AppScan CodeSweep
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
