name: Super-Linter

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_PYTHON: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
